const ArrayOfItem = [
    {
        id:1,
        name:"balram",
        age:25,
        gender:"male"
    },
    {
        id:2,
        name:"neeraj",
        age:32,
        gender:"male"
    },
    {
        id:3,
        name:"suraj",
        age:39,
        gender:"male"
    },
    {
        id:4,
        name:"shara",
        age:37,
        gender:"Female"
    },
    {
        id:5,
        name:"simmi",
        age:35,
        gender:"Female"
    },
    {
        id:6,
        name:"shimran",
        age:30,
        gender:"Female"
    },
    {
        id:7,
        name:"santosh",
        age: 45,
        gender:"male"
    },
    {
        id:8,
        name:"rani",
        age:40,
        gender:"Female"
    },
    {
        id:9,
        name:"radhe",
        age:65,
        gender:"male"
    },
    {
        id:10,
        name:"rita",
        age: 55,
        gender:"Female"
    },
    {
        id:11,
        name:"gita",
        age:60,
        gender:"Female"
    },
    {
        id:12,
        name:"gaurabh",
        age:50,
        gender:"male"
    },
    {
        id:13,
        name:"balram",
        age:25,
        gender:"male"
    },
    {
        id:14,
        name:"neeraj",
        age:32,
        gender:"male"
    },
    {
        id:15,
        name:"suraj",
        age:39,
        gender:"male"
    },
    {
        id:16,
        name:"shara",
        age:37,
        gender:"Female"
    },
    {
        id:17,
        name:"simmi",
        age:35,
        gender:"Female"
    },
    {
        id:18,
        name:"shimran",
        age:30,
        gender:"Female"
    },
    {
        id:19,
        name:"santosh",
        age: 45,
        gender:"male"
    },
    {
        id:20,
        name:"rani",
        age:40,
        gender:"Female"
    },
    {
        id:21,
        name:"radhe",
        age:65,
        gender:"male"
    },
    {
        id:22,
        name:"rita",
        age: 55,
        gender:"Female"
    },
    {
        id:23,
        name:"gita",
        age:60,
        gender:"Female"
    },
    {
        id:24,
        name:"gaurabh",
        age:50,
        gender:"male"
    }
]

export default ArrayOfItem